const games = [
    { name: "Bowmasters", url: "https://ander55555.github.io/games/bowmasters.html" },
    { name: "OvO", url: "https://ander55555.github.io/games/ovo.html" },
    { name: "OvO 2", url: "https://ander55555.github.io/games/ovo-2.html" },
    { name: "OvO 3 Dimensions", url: "https://ander55555.github.io/games/ovo-3-dimensions.html" },
    { name: "Gladihoppers", url: "https://ander55555.github.io/games/gladihoppers.html" },
    { name: "Ice Dodo", url: "https://ander55555.github.io/games/ice-dodo.html" },
    { name: "Block Blast", url: "https://ander55555.github.io/games/block-blast.html" },
    { name: "Jetpack Joyride", url: "https://ander55555.github.io/games/jetpack-joyride.html" },
    { name: "Friday Night Funkin", url: "https://ander55555.github.io/games/friday-night-funkin.html" },
    { name: "Sprunki", url: "https://ander55555.github.io/games/sprunki.html" },
    { name: "Temple Run 2", url: "https://ander55555.github.io/games/temple-run-2.html" },
    { name: "Stickman Hook", url: "https://ander55555.github.io/games/stickman-hook.html" },
    { name: "Attack Hole", url: "https://ander55555.github.io/games/attack-hole.html" },
    { name: "Bridge Race", url: "https://ander55555.github.io/games/bridge-race.html" },
    { name: "Color Water Sort 3D", url: "https://ander55555.github.io/games/color-water-sort-3d.html" },
    { name: "Hide N Seek", url: "https://ander55555.github.io/games/hide-n-seek.html" },
    { name: "Magic Tiles 3", url: "https://ander55555.github.io/games/magic-tiles-3.html" },
    { name: "Stacky Dash", url: "https://ander55555.github.io/games/stacky-dash.html" },
    { name: "Supreme Duelist", url: "https://ander55555.github.io/games/supreme-duelist.html" },
    { name: "Tall Man Run", url: "https://ander55555.github.io/games/tall-man-run.html" },
    { name: "Turbo Stars", url: "https://ander55555.github.io/games/turbo-stars.html" },
    { name: "Mob Control HTML5", url: "https://ander55555.github.io/games/mob-control-html5.html" },
    { name: "Pou", url: "https://ander55555.github.io/games/pou.html" },
    { name: "Crossy Road", url: "https://ander55555.github.io/games/crossy-road.html" },
    { name: "Basket Battle", url: "https://ander55555.github.io/games/basket-battle.html" },
    { name: "Amaze", url: "https://ander55555.github.io/games/amaze.html" },
    { name: "Geometry Dash Lite", url: "https://ander55555.github.io/games/geometry-dash-lite.html" },
    { name: "Basketball Frvr", url: "https://ander55555.github.io/games/basketball-frvr.html" },
    { name: "Bazooka Boy", url: "https://ander55555.github.io/games/bazooka-boy.html" },
    { name: "Bottle Jump 3D", url: "https://ander55555.github.io/games/bottle-jump-3d.html" },
    { name: "Color Match", url: "https://ander55555.github.io/games/color-match.html" },
    { name: "Dig Deep", url: "https://ander55555.github.io/games/dig-deep.html" },
    { name: "Retro Bowl", url: "https://ander55555.github.io/games/retro-bowl.html" },
    { name: "Retro Bowl College", url: "https://ander55555.github.io/games/retro-bowl-college.html" },
    { name: "Monster Tracks", url: "https://ander55555.github.io/games/monster-tracks.html" },
    { name: "Gobble", url: "https://ander55555.github.io/games/gobble.html" },
    { name: "Five Nights at Freddy's", url: "https://ander55555.github.io/games/five-nights-at-freddy-s.html" },
    { name: "Five Nights at Freddy's 2", url: "https://ander55555.github.io/games/five-nights-at-freddy-s-2.html" },
    { name: "Five Nights at Freddy's 3", url: "https://ander55555.github.io/games/five-nights-at-freddy-s-3.html" },
    { name: "Five Nights at Freddy's 4", url: "https://ander55555.github.io/games/five-nights-at-freddy-s-4.html" },
    { name: "Road of Fury", url: "https://ander55555.github.io/games/road-of-fury.html" },
    { name: "Driven Wild", url: "https://ander55555.github.io/games/driven-wild.html" },
    { name: "Ragdoll Hit", url: "https://ander55555.github.io/games/ragdoll-hit.html" },
    { name: "Vex 1", url: "https://ander55555.github.io/games/vex-1.html" },
    { name: "Vex 2", url: "https://ander55555.github.io/games/vex-2.html" },
    { name: "Vex 3", url: "https://ander55555.github.io/games/vex-3.html" },
    { name: "Vex 3 XMAS", url: "https://ander55555.github.io/games/vex-3-xmas.html" },
    { name: "Vex 4", url: "https://ander55555.github.io/games/vex-4.html" },
    { name: "Vex 5", url: "https://ander55555.github.io/games/vex-5.html" },
    { name: "Vex 6", url: "https://ander55555.github.io/games/vex-6.html" },
    { name: "Vex 7", url: "https://ander55555.github.io/games/vex-7.html" },
    { name: "Vex 8", url: "https://ander55555.github.io/games/vex-8.html" },
    { name: "Vex Challenges", url: "https://ander55555.github.io/games/vex-challenges.html" },
    { name: "Vex X3M", url: "https://ander55555.github.io/games/vex-x3m.html" },
    { name: "Vex X3M 2", url: "https://ander55555.github.io/games/vex-x3m-2.html" },
    { name: "1v1.LoL", url: "https://ander55555.github.io/games/1v1-lol.html" },
    { name: "A Dance of Fire and Ice", url: "https://ander55555.github.io/games/a-dance-of-fire-and-ice.html" },
    { name: "Achievement Unlocked", url: "https://ander55555.github.io/games/achievement-unlocked.html" },
    { name: "Achievement Unlocked 2", url: "https://ander55555.github.io/games/achievement-unlocked-2.html" },
    { name: "Achievement Unlocked 3", url: "https://ander55555.github.io/games/achievement-unlocked-3.html" },
    { name: "Angry Birds", url: "https://ander55555.github.io/games/angry-birds.html" },
    { name: "Backrooms", url: "https://ander55555.github.io/games/backrooms.html" },
    { name: "Baldi's Basics", url: "https://ander55555.github.io/games/baldi-s-basics.html" },
    { name: "Basket Random", url: "https://ander55555.github.io/games/basket-random.html" },
    { name: "Big Tower Tiny Square", url: "https://ander55555.github.io/games/big-tower-tiny-square.html" },
    { name: "Big NEON Tower Tiny Square", url: "https://ander55555.github.io/games/big-neon-tower-tiny-square.html" },
    { name: "Big ICE Tower Tiny Square", url: "https://ander55555.github.io/games/big-ice-tower-tiny-square.html" },
    { name: "BitLife", url: "https://ander55555.github.io/games/bitlife.html" },
    { name: "Bloons TD", url: "https://ander55555.github.io/games/bloons-td.html" },
    { name: "Bloons TD 2", url: "https://ander55555.github.io/games/bloons-td-2.html" },
    { name: "Bloons TD 3", url: "https://ander55555.github.io/games/bloons-td-3.html" },
    { name: "Bloons TD 4", url: "https://ander55555.github.io/games/bloons-td-4.html" },
    { name: "Bloons TD 5", url: "https://ander55555.github.io/games/bloons-td-5.html" },
    { name: "Bob The Robber 2", url: "https://ander55555.github.io/games/bob-the-robber-2.html" },
    { name: "Boxing Random", url: "https://ander55555.github.io/games/boxing-random.html" },
    { name: "Burrito Bison", url: "https://ander55555.github.io/games/burrito-bison.html" },
    { name: "Cannon Basketball", url: "https://ander55555.github.io/games/cannon-basketball.html" },
    { name: "Cannon Basketball 2", url: "https://ander55555.github.io/games/cannon-basketball-2.html" },
    { name: "Cluster Rush", url: "https://ander55555.github.io/games/cluster-rush.html" },
    { name: "Cookie Clicker", url: "https://ander55555.github.io/games/cookie-clicker.html" },
    { name: "Coreball", url: "https://ander55555.github.io/games/coreball.html" },
    { name: "Cubefield", url: "https://ander55555.github.io/games/cubefield.html" },
    { name: "Cut the Rope", url: "https://ander55555.github.io/games/cut-the-rope.html" },
    { name: "Draw Climber", url: "https://ander55555.github.io/games/draw-climber.html" },
    { name: "Emulator.JS", url: "https://ander55555.github.io/games/emulator-js.html" },
    { name: "Fireboy and Watergirl 2", url: "https://ander55555.github.io/games/fireboy-and-watergirl-2.html" },
    { name: "Fireboy and Watergirl 3", url: "https://ander55555.github.io/games/fireboy-and-watergirl-3.html" },
    { name: "Granny", url: "https://ander55555.github.io/games/granny.html" },
    { name: "Gunspin", url: "https://ander55555.github.io/games/gunspin.html" },
    { name: "Highway Racer 2", url: "https://ander55555.github.io/games/highway-racer-2.html" },
    { name: "Johnny Trigger", url: "https://ander55555.github.io/games/johnny-trigger.html" },
    { name: "Journey Downhill", url: "https://ander55555.github.io/games/journey-downhill.html" },
    { name: "Line Rider", url: "https://ander55555.github.io/games/line-rider.html" },
    { name: "Moto X3M", url: "https://ander55555.github.io/games/moto-x3m.html" },
    { name: "Moto X3M 2", url: "https://ander55555.github.io/games/moto-x3m-2.html" },
    { name: "Moto X3M 3", url: "https://ander55555.github.io/games/moto-x3m-3.html" },
    { name: "Moto X3M Spooky", url: "https://ander55555.github.io/games/moto-x3m-spooky.html" },
    { name: "Moto X3M Winter", url: "https://ander55555.github.io/games/moto-x3m-winter.html" },
    { name: "Ninja vs EvilCorp", url: "https://ander55555.github.io/games/ninja-vs-evilcorp.html" },
    { name: "Paper.io 2", url: "https://ander55555.github.io/games/paper-io-2.html" },
    { name: "The World's Hardest Game", url: "https://ander55555.github.io/games/the-world-s-hardest-game.html" },
    { name: "The World's Hardest Game 3", url: "https://ander55555.github.io/games/the-world-s-hardest-game-3.html" },
    { name: "The World's Hardest Game 4", url: "https://ander55555.github.io/games/the-world-s-hardest-game-4.html" },
    { name: "This Is The Only Level", url: "https://ander55555.github.io/games/this-is-the-only-level.html" },
    { name: "This Is The Only Level 2", url: "https://ander55555.github.io/games/this-is-the-only-level-2.html" },
    { name: "Tiny Fishing", url: "https://ander55555.github.io/games/tiny-fishing.html" },
    { name: "Tomb Of The Mask", url: "https://ander55555.github.io/games/tomb-of-the-mask.html" },
    { name: "Toss The Turtle", url: "https://ander55555.github.io/games/toss-the-turtle.html" },
    { name: "Tube Jumpers", url: "https://ander55555.github.io/games/tube-jumpers.html" },
    { name: "Wordle", url: "https://ander55555.github.io/games/wordle.html" },
    { name: "Ruffle", url: "https://ander55555.github.io/games/ruffle.html" },
    { name: "2048", url: "https://ander55555.github.io/games/2048.html" },
    { name: "8 Ball Pool", url: "https://ander55555.github.io/games/8-ball-pool.html" },
    { name: "Offroad Mountain Bike", url: "https://ander55555.github.io/games/offroad-mountain-bike.html" },
    { name: "Space Waves", url: "https://ander55555.github.io/games/space-waves.html" },
    { name: "Solar Smash", url: "https://ander55555.github.io/games/solar-smash.html" },
    { name: "Snow Rider 3D", url: "https://ander55555.github.io/games/snow-rider-3d.html" },
    { name: "Fortzone Battle Royale", url: "https://ander55555.github.io/games/fortzone-battle-royale.html" },
    { name: "Brawl Guys.io", url: "https://ander55555.github.io/games/brawl-guys-io.html" },
    { name: "Survival Race", url: "https://ander55555.github.io/games/survival-race.html" },
    { name: "Poly Track", url: "https://ander55555.github.io/games/poly-track.html" },
    { name: "Moto X3M Pool Party", url: "https://ander55555.github.io/games/moto-x3m-pool-party.html" },
    { name: "Granny 2", url: "https://ander55555.github.io/games/granny-2.html" },
    { name: "Granny 3", url: "https://ander55555.github.io/games/granny-3.html" },
    { name: "Fashion Battle", url: "https://ander55555.github.io/games/fashion-battle.html" },
    { name: "Slice it All", url: "https://ander55555.github.io/games/slice-it-all.html" },
    { name: "Flappy Bird", url: "https://ander55555.github.io/games/flappy-bird.html" },
    { name: "osu!", url: "https://ander55555.github.io/games/osu.html" },
    { name: "8 Ball Classic", url: "https://ander55555.github.io/games/8-ball-classic.html" },
    { name: "Angry Birds Showdown", url: "https://ander55555.github.io/games/angry-birds-showdown.html" },
    { name: "Archery World Tour", url: "https://ander55555.github.io/games/archery-world-tour.html" },
    { name: "Ball Blast", url: "https://ander55555.github.io/games/ball-blast.html" },
    { name: "Cannon Balls 3D", url: "https://ander55555.github.io/games/cannon-balls-3d.html" },
    { name: "Chess Classic", url: "https://ander55555.github.io/games/chess-classic.html" },
    { name: "Draw the Line", url: "https://ander55555.github.io/games/draw-the-line.html" },
    { name: "Flappy Dunk", url: "https://ander55555.github.io/games/flappy-dunk.html" },
    { name: "Fork n Sausage", url: "https://ander55555.github.io/games/fork-n-sausage.html" },
    { name: "Guess Their Answer", url: "https://ander55555.github.io/games/guess-their-answer.html" },
    { name: "Harvest.io", url: "https://ander55555.github.io/games/harvest-io.html" },
    { name: "Hill Climb Racing Lite", url: "https://ander55555.github.io/games/hill-climb-racing-lite.html" },
    { name: "Pac-Man Superfast", url: "https://ander55555.github.io/games/pac-man-superfast.html" },
    { name: "Parking Rush", url: "https://ander55555.github.io/games/parking-rush.html" },
    { name: "Race Master 3D", url: "https://ander55555.github.io/games/race-master-3d.html" },
    { name: "State.io", url: "https://ander55555.github.io/games/state-io.html" },
    { name: "Tower Crash 3D", url: "https://ander55555.github.io/games/tower-crash-3d.html" },
    { name: "Trivia Crack", url: "https://ander55555.github.io/games/trivia-crack.html" },
    { name: "Crazy Cattle 3D", url: "https://ander55555.github.io/games/crazy-cattle-3d.html" },
    { name: "Cheese Chompers 3D", url: "https://ander55555.github.io/games/cheese-chompers-3d.html" },
    { name: "Bad Parenting 1", url: "https://ander55555.github.io/games/bad-parenting-1.html" },
    { name: "Blade Ball", url: "https://ander55555.github.io/games/blade-ball.html" },
    { name: "Blocky Snakes", url: "https://ander55555.github.io/games/blocky-snakes.html" },
    { name: "Bloxorz", url: "https://ander55555.github.io/games/bloxorz.html" },
    { name: "Big Tower Tiny Square 2", url: "https://ander55555.github.io/games/big-tower-tiny-square-2.html" },
    { name: "Candy Crush", url: "https://ander55555.github.io/games/candy-crush.html" },
    { name: "Melon Playground", url: "https://ander55555.github.io/games/melon-playground.html" },
    { name: "Drift Hunters", url: "https://ander55555.github.io/games/drift-hunters.html" },
    { name: "World Box", url: "https://ander55555.github.io/games/world-box.html" },
    { name: "Run 1", url: "https://ander55555.github.io/games/run-1.html" },
    { name: "Run 2", url: "https://ander55555.github.io/games/run-2.html" },
    { name: "Run 3", url: "https://ander55555.github.io/games/run-3.html" },
    { name: "Swords and Souls", url: "https://ander55555.github.io/games/swords-and-souls.html" },
    { name: "Soundboard", url: "https://ander55555.github.io/games/soundboard.html" },
    { name: "n-gon", url: "https://ander55555.github.io/games/n-gon.html" },
    { name: "Minecraft 1.8.8", url: "https://ander55555.github.io/games/minecraft-1-8-8.html" },
    { name: "Minecraft 1.12.2", url: "https://ander55555.github.io/games/minecraft-1-12-2.html" },
    { name: "Minecraft 1.21.4", url: "https://ander55555.github.io/games/minecraft-1-21-4.html" },
    { name: "Five Nights at Freddy's: Sister Location", url: "https://ander55555.github.io/games/five-nights-at-freddy-s-sister-location.html" },
    { name: "Ragdoll Archers", url: "https://ander55555.github.io/games/ragdoll-archers.html" },
    { name: "Papers, Please", url: "https://ander55555.github.io/games/papers-please.html" },
    { name: "Scrap Metal 3", url: "https://ander55555.github.io/games/scrap-metal-3.html" },
    { name: "Five Nights at Freddy's: World", url: "https://ander55555.github.io/games/five-nights-at-freddy-s-world.html" },
    { name: "Five Nights at Freddy's: Pizza Simulator", url: "https://ander55555.github.io/games/five-nights-at-freddy-s-pizza-simulator.html" },
    { name: "Five Nights at Freddy's: Ultimate Custom Night", url: "https://ander55555.github.io/games/five-nights-at-freddy-s-ultimate-custom-night.html" },
    { name: "Do NOT Take This Cat Home", url: "https://ander55555.github.io/games/do-not-take-this-cat-home.html" },
    { name: "People Playground", url: "https://ander55555.github.io/games/people-playground.html" },
    { name: "R.E.P.O", url: "https://ander55555.github.io/games/r-e-p-o.html" },
    { name: "ULTRAKILL", url: "https://ander55555.github.io/games/ultrakill.html" },
    { name: "Elastic Man", url: "https://ander55555.github.io/games/elastic-man.html" },
    { name: "Slope", url: "https://ander55555.github.io/games/slope.html" },
    { name: "Time Shooter 1", url: "https://ander55555.github.io/games/time-shooter-1.html" },
    { name: "Time Shooter 2", url: "https://ander55555.github.io/games/time-shooter-2.html" },
    { name: "Time Shooter 3: SWAT", url: "https://ander55555.github.io/games/time-shooter-3-swat.html" },
    { name: "Carrom Clash", url: "https://ander55555.github.io/games/carrom-clash.html" },
    { name: "DOOM", url: "https://ander55555.github.io/games/doom.html" },
    { name: "Five Nights at Winston's", url: "https://ander55555.github.io/games/five-nights-at-winston-s.html" },
    { name: "Buckshot Roulette", url: "https://ander55555.github.io/games/buckshot-roulette.html" },
    { name: "Tunnel Rush", url: "https://ander55555.github.io/games/tunnel-rush.html" },
    { name: "Snowbattle.io", url: "https://ander55555.github.io/games/snowbattle-io.html" },
    { name: "Rolly Vortex", url: "https://ander55555.github.io/games/rolly-vortex.html" },
    { name: "Draw the Hill", url: "https://ander55555.github.io/games/draw-the-hill.html" },
    { name: "Dragon vs Bricks", url: "https://ander55555.github.io/games/dragon-vs-bricks.html" },
    { name: "Death Run 3D", url: "https://ander55555.github.io/games/death-run-3d.html" },
    { name: "Cut the Rope", url: "https://ander55555.github.io/games/cut-the-rope.html" },
    { name: "Cut the Rope: Time Travel", url: "https://ander55555.github.io/games/cut-the-rope-time-travel.html" },
    { name: "Cut the Rope: Holiday Gift", url: "https://ander55555.github.io/games/cut-the-rope-holiday-gift.html" },
    { name: "Bendy and the Ink Machine", url: "https://ander55555.github.io/games/bendy-and-the-ink-machine.html" },
    { name: "That's Not My Neighbor", url: "https://ander55555.github.io/games/that-s-not-my-neighbor.html" },
    { name: "Hotline Miami", url: "https://ander55555.github.io/games/hotline-miami.html" },
    { name: "Papa's Bakeria", url: "https://ander55555.github.io/games/papa-s-bakeria.html" },
    { name: "Papa's Burgeria", url: "https://ander55555.github.io/games/papa-s-burgeria.html" },
    { name: "Papa's Cheeseria", url: "https://ander55555.github.io/games/papa-s-cheeseria.html" },
    { name: "Papa's Cupcakeria", url: "https://ander55555.github.io/games/papa-s-cupcakeria.html" },
    { name: "Papa's Donuteria", url: "https://ander55555.github.io/games/papa-s-donuteria.html" },
    { name: "Papa's Freezeria", url: "https://ander55555.github.io/games/papa-s-freezeria.html" },
    { name: "Papa's Hot Doggeria", url: "https://ander55555.github.io/games/papa-s-hot-doggeria.html" },
    { name: "Papa's Pancakeria", url: "https://ander55555.github.io/games/papa-s-pancakeria.html" },
    { name: "Papa's Pastaria", url: "https://ander55555.github.io/games/papa-s-pastaria.html" },
    { name: "Papa's Pizeria", url: "https://ander55555.github.io/games/papa-s-pizeria.html" },
    { name: "Papa's Scooperia", url: "https://ander55555.github.io/games/papa-s-scooperia.html" },
    { name: "Papa's Sushiria", url: "https://ander55555.github.io/games/papa-s-sushiria.html" },
    { name: "Papa's Taco Mia", url: "https://ander55555.github.io/games/papa-s-taco-mia.html" },
    { name: "Papa's Wingeria", url: "https://ander55555.github.io/games/papa-s-wingeria.html" },
    { name: "Plants vs Zombies", url: "https://ander55555.github.io/games/plants-vs-zombies.html" },
    { name: "Superhot", url: "https://ander55555.github.io/games/superhot.html" },
    { name: "Duck Life", url: "https://ander55555.github.io/games/duck-life.html" },
    { name: "Duck Life 2", url: "https://ander55555.github.io/games/duck-life-2.html" },
    { name: "Duck Life 3", url: "https://ander55555.github.io/games/duck-life-3.html" },
    { name: "Duck Life 4", url: "https://ander55555.github.io/games/duck-life-4.html" },
    { name: "Duck Life 5", url: "https://ander55555.github.io/games/duck-life-5.html" },
    { name: "Red Ball", url: "https://ander55555.github.io/games/red-ball.html" },
    { name: "Red Ball 2", url: "https://ander55555.github.io/games/red-ball-2.html" },
    { name: "Red Ball 3", url: "https://ander55555.github.io/games/red-ball-3.html" },
    { name: "Red Ball 4", url: "https://ander55555.github.io/games/red-ball-4.html" },
    { name: "Red Ball 4 Vol. 2", url: "https://ander55555.github.io/games/red-ball-4-vol-2.html" },
    { name: "Red Ball 4 Vol. 3", url: "https://ander55555.github.io/games/red-ball-4-vol-3.html" },
    { name: "Wheely", url: "https://ander55555.github.io/games/wheely.html" },
    { name: "Wheely 2", url: "https://ander55555.github.io/games/wheely-2.html" },
    { name: "Wheely 3", url: "https://ander55555.github.io/games/wheely-3.html" },
    { name: "Wheely 4", url: "https://ander55555.github.io/games/wheely-4.html" },
    { name: "Wheely 5", url: "https://ander55555.github.io/games/wheely-5.html" },
    { name: "Wheely 6", url: "https://ander55555.github.io/games/wheely-6.html" },
    { name: "Wheely 7", url: "https://ander55555.github.io/games/wheely-7.html" },
    { name: "Wheely 8", url: "https://ander55555.github.io/games/wheely-8.html" },
    { name: "Chat Bot (A.|.I)", url: "https://ander55555.github.io/games/chat-bot-a-i.html" },
    { name: "Crazy Chicken 3D", url: "https://ander55555.github.io/games/crazy-chicken-3d.html" },
    { name: "Crazy Kitty 3D", url: "https://ander55555.github.io/games/crazy-kitty-3d.html" },
    { name: "Google Baseball", url: "https://ander55555.github.io/games/google-baseball.html" },
    { name: "A Bite at Freddy's", url: "https://ander55555.github.io/games/a-bite-at-freddy-s.html" },
    { name: "Class of '09", url: "https://ander55555.github.io/games/class-of-09.html" },
    { name: "RE:RUN", url: "https://ander55555.github.io/games/re-run.html" },
    { name: "Fruit Ninja", url: "https://ander55555.github.io/games/fruit-ninja.html" },
    { name: "Half Life", url: "https://ander55555.github.io/games/half-life.html" },
    { name: "Quake III Arena", url: "https://ander55555.github.io/games/quake-iii-arena.html" },
    { name: "Escape Road", url: "https://ander55555.github.io/games/escape-road.html" },
    { name: "Escape Road 2", url: "https://ander55555.github.io/games/escape-road-2.html" },
    { name: "Speed Stars", url: "https://ander55555.github.io/games/speed-stars.html" },
    { name: "Pizza Tower", url: "https://ander55555.github.io/games/pizza-tower.html" },
    { name: "Bacon May Die", url: "https://ander55555.github.io/games/bacon-may-die.html" },
    { name: "Bad Ice Cream", url: "https://ander55555.github.io/games/bad-ice-cream.html" },
    { name: "Bad Ice Cream 2", url: "https://ander55555.github.io/games/bad-ice-cream-2.html" },
    { name: "Bad Ice Cream 3", url: "https://ander55555.github.io/games/bad-ice-cream-3.html" },
    { name: "Basketball Stars", url: "https://ander55555.github.io/games/basketball-stars.html" },
    { name: "BlockPost", url: "https://ander55555.github.io/games/blockpost.html" },
    { name: "CircloO", url: "https://ander55555.github.io/games/circloo.html" },
    { name: "CircloO 2", url: "https://ander55555.github.io/games/circloo-2.html" },
    { name: "Drift Boss", url: "https://ander55555.github.io/games/drift-boss.html" },
    { name: "Evil Glitch", url: "https://ander55555.github.io/games/evil-glitch.html" },
    { name: "Madalin Stunt Cars 2", url: "https://ander55555.github.io/games/madalin-stunt-cars-2.html" },
    { name: "Madalin Stunt Cars 3", url: "https://ander55555.github.io/games/madalin-stunt-cars-3.html" },
    { name: "Papery Planes", url: "https://ander55555.github.io/games/papery-planes.html" },
    { name: "Pixel Gun Survival", url: "https://ander55555.github.io/games/pixel-gun-survival.html" },
    { name: "Protektor", url: "https://ander55555.github.io/games/protektor.html" },
    { name: "Rooftop Snipers", url: "https://ander55555.github.io/games/rooftop-snipers.html" },
    { name: "War The Knights", url: "https://ander55555.github.io/games/war-the-knights.html" },
    { name: "Basket Bros", url: "https://ander55555.github.io/games/basket-bros.html" },
    { name: "Endoparasitic", url: "https://ander55555.github.io/games/endoparasitic.html" },
    { name: "Riddle School", url: "https://ander55555.github.io/games/riddle-school.html" },
    { name: "Riddle School 2", url: "https://ander55555.github.io/games/riddle-school-2.html" },
    { name: "Riddle School 3", url: "https://ander55555.github.io/games/riddle-school-3.html" },
    { name: "Riddle School 4", url: "https://ander55555.github.io/games/riddle-school-4.html" },
    { name: "Riddle School 5", url: "https://ander55555.github.io/games/riddle-school-5.html" },
    { name: "Riddle Transfer", url: "https://ander55555.github.io/games/riddle-transfer.html" },
    { name: "Riddle Transfer 2", url: "https://ander55555.github.io/games/riddle-transfer-2.html" },
    { name: "Idle Dice", url: "https://ander55555.github.io/games/idle-dice.html" },
    { name: "12 Mini Battles", url: "https://ander55555.github.io/games/12-mini-battles.html" },
    { name: "Play!.js", url: "https://ander55555.github.io/games/play-js.html" },
    { name: "Minecraft 1.5.2", url: "https://ander55555.github.io/games/minecraft-1-5-2.html" },
    { name: "Minecraft Alpha 1.2.6", url: "https://ander55555.github.io/games/minecraft-alpha-1-2-6.html" },
    { name: "Minecraft Beta 1.3", url: "https://ander55555.github.io/games/minecraft-beta-1-3.html" },
    { name: "Minecraft Beta 1.7.3", url: "https://ander55555.github.io/games/minecraft-beta-1-7-3.html" },
    { name: "Minecraft Indev", url: "https://ander55555.github.io/games/minecraft-indev.html" },
    { name: "Little Runmo", url: "https://ander55555.github.io/games/little-runmo.html" },
    { name: "Territorial.io", url: "https://ander55555.github.io/games/territorial-io.html" },
    { name: "Alien Hominid", url: "https://ander55555.github.io/games/alien-hominid.html" },
    { name: "Tanuki Sunset", url: "https://ander55555.github.io/games/tanuki-sunset.html" },
    { name: "Shipo.io", url: "https://ander55555.github.io/games/shipo-io.html" },
    { name: "Rainbow Obby", url: "https://ander55555.github.io/games/rainbow-obby.html" },
    { name: "Nazi Zombies: Portable", url: "https://ander55555.github.io/games/nazi-zombies-portable.html" },
    { name: "Sandboxels", url: "https://ander55555.github.io/games/sandboxels.html" },
    { name: "Dreadhead Parkour", url: "https://ander55555.github.io/games/dreadhead-parkour.html" },
    { name: "Sandtris", url: "https://ander55555.github.io/games/sandtris.html" },
    { name: "BlackJack", url: "https://ander55555.github.io/games/blackjack.html" },
    { name: "Minesweeper Mania", url: "https://ander55555.github.io/games/minesweeper-mania.html" },
    { name: "Super Mario 63", url: "https://ander55555.github.io/games/super-mario-63.html" },
    { name: "Jelly Mario", url: "https://ander55555.github.io/games/jelly-mario.html" },
    { name: "Angry Birds Chrome", url: "https://ander55555.github.io/games/angry-birds-chrome.html" },
    { name: "sandspiel", url: "https://ander55555.github.io/games/sandspiel.html" },
    { name: "Side Effects", url: "https://ander55555.github.io/games/side-effects.html" },
    { name: "Build a Queen", url: "https://ander55555.github.io/games/build-a-queen.html" },
    { name: "3D Bowling", url: "https://ander55555.github.io/games/3d-bowling.html" },
    { name: "Room Sort", url: "https://ander55555.github.io/games/room-sort.html" },
    { name: "Sushi Roll", url: "https://ander55555.github.io/games/sushi-roll.html" },
    { name: "Find the Alien", url: "https://ander55555.github.io/games/find-the-alien.html" },
    { name: "Maze Speedrun", url: "https://ander55555.github.io/games/maze-speedrun.html" },
    { name: "Kitchen Bazar", url: "https://ander55555.github.io/games/kitchen-bazar.html" },
    { name: "Pokey Ball", url: "https://ander55555.github.io/games/pokey-ball.html" },
    { name: "Slime.io", url: "https://ander55555.github.io/games/slime-io.html" },
    { name: "Om Nom Run", url: "https://ander55555.github.io/games/om-nom-run.html" },
    { name: "TileTopia", url: "https://ander55555.github.io/games/tiletopia.html" },
    { name: "BitPlanes", url: "https://ander55555.github.io/games/bitplanes.html" },
    { name: "Crazy Cars", url: "https://ander55555.github.io/games/crazy-cars.html" },
    { name: "Fancy Pants Adventure", url: "https://ander55555.github.io/games/fancy-pants-adventure.html" },
    { name: "Fancy Pants Adventure 2", url: "https://ander55555.github.io/games/fancy-pants-adventure-2.html" },
    { name: "Fancy Pants Adventure 3", url: "https://ander55555.github.io/games/fancy-pants-adventure-3.html" },
    { name: "Fancy Pants Adventure 4 Part 1", url: "https://ander55555.github.io/games/fancy-pants-adventure-4-part-1.html" },
    { name: "Fancy Pants Adventure 4 Part 2", url: "https://ander55555.github.io/games/fancy-pants-adventure-4-part-2.html" },
    { name: "Getaway Shootout", url: "https://ander55555.github.io/games/getaway-shootout.html" },
    { name: "House of Hazards", url: "https://ander55555.github.io/games/house-of-hazards.html" },
    { name: "Learn to Fly", url: "https://ander55555.github.io/games/learn-to-fly.html" },
    { name: "Learn to Fly 2", url: "https://ander55555.github.io/games/learn-to-fly-2.html" },
    { name: "Learn to Fly 3", url: "https://ander55555.github.io/games/learn-to-fly-3.html" },
    { name: "Learn to Fly Idle", url: "https://ander55555.github.io/games/learn-to-fly-idle.html" },
    { name: "Raft Wars", url: "https://ander55555.github.io/games/raft-wars.html" },
    { name: "Raft Wars 2", url: "https://ander55555.github.io/games/raft-wars-2.html" },
    { name: "Sort the Court", url: "https://ander55555.github.io/games/sort-the-court.html" },
    { name: "SpiderDoll", url: "https://ander55555.github.io/games/spiderdoll.html" },
    { name: "They Are Coming", url: "https://ander55555.github.io/games/they-are-coming.html" },
    { name: "Spiral Roll", url: "https://ander55555.github.io/games/spiral-roll.html" },
    { name: "Binding of Issac: Wrath of the Lamb", url: "https://ander55555.github.io/games/binding-of-issac-wrath-of-the-lamb.html" },
    { name: "Happy Sheepies", url: "https://ander55555.github.io/games/happy-sheepies.html" },
    { name: "DON'T YOU LECTURE ME", url: "https://ander55555.github.io/games/don-t-you-lecture-me.html" },
    { name: "Blumgi Rocket", url: "https://ander55555.github.io/games/blumgi-rocket.html" },
    { name: "Adventure Capatalist", url: "https://ander55555.github.io/games/adventure-capatalist.html" },
    { name: "Dadish 2", url: "https://ander55555.github.io/games/dadish-2.html" },
    { name: "Dadish 3", url: "https://ander55555.github.io/games/dadish-3.html" },
    { name: "Dadish", url: "https://ander55555.github.io/games/dadish.html" },
    { name: "Dadish 3D", url: "https://ander55555.github.io/games/dadish-3d.html" },
    { name: "Daily Dadish", url: "https://ander55555.github.io/games/daily-dadish.html" },
    { name: "EvoWars.io", url: "https://ander55555.github.io/games/evowars-io.html" },
    { name: "Google Feud", url: "https://ander55555.github.io/games/google-feud.html" },
    { name: "Idle Breakout", url: "https://ander55555.github.io/games/idle-breakout.html" },
    { name: "Idle Lumber Inc", url: "https://ander55555.github.io/games/idle-lumber-inc.html" },
    { name: "Idle Mining Empire", url: "https://ander55555.github.io/games/idle-mining-empire.html" },
    { name: "JustFall.lol", url: "https://ander55555.github.io/games/justfall-lol.html" },
    { name: "Merge Harvest", url: "https://ander55555.github.io/games/merge-harvest.html" },
    { name: "Parking Fury 3D", url: "https://ander55555.github.io/games/parking-fury-3d.html" },
    { name: "Slope 2", url: "https://ander55555.github.io/games/slope-2.html" },
    { name: "Slowroads", url: "https://ander55555.github.io/games/slowroads.html" },
    { name: "Smash Karts", url: "https://ander55555.github.io/games/smash-karts.html" },
    { name: "Stickman Fight Ragdoll", url: "https://ander55555.github.io/games/stickman-fight-ragdoll.html" },
    { name: "Stickman Boost", url: "https://ander55555.github.io/games/stickman-boost.html" },
    { name: "Stickman Climb", url: "https://ander55555.github.io/games/stickman-climb.html" },
    { name: "Stickman Golf", url: "https://ander55555.github.io/games/stickman-golf.html" },
    { name: "2048 Merge Run", url: "https://ander55555.github.io/games/2048-merge-run.html" },
    { name: "Build a Big Army", url: "https://ander55555.github.io/games/build-a-big-army.html" },
    { name: "Build a Plane", url: "https://ander55555.github.io/games/build-a-plane.html" },
    { name: "Camouflage and Sniper", url: "https://ander55555.github.io/games/camouflage-and-sniper.html" },
    { name: "Car Survival 3D", url: "https://ander55555.github.io/games/car-survival-3d.html" },
    { name: "City Defense", url: "https://ander55555.github.io/games/city-defense.html" },
    { name: "Clothing Shop 3D", url: "https://ander55555.github.io/games/clothing-shop-3d.html" },
    { name: "Cool Cars Run 3D", url: "https://ander55555.github.io/games/cool-cars-run-3d.html" },
    { name: "Crush Cars 3D", url: "https://ander55555.github.io/games/crush-cars-3d.html" },
    { name: "Destiny Run 3D", url: "https://ander55555.github.io/games/destiny-run-3d.html" },
    { name: "Destroy The Car 3D", url: "https://ander55555.github.io/games/destroy-the-car-3d.html" },
    { name: "Diamond Seeker", url: "https://ander55555.github.io/games/diamond-seeker.html" },
    { name: "Draw Joust", url: "https://ander55555.github.io/games/draw-joust.html" },
    { name: "Evolving Bombs 3D", url: "https://ander55555.github.io/games/evolving-bombs-3d.html" },
    { name: "Fire and Frost Master", url: "https://ander55555.github.io/games/fire-and-frost-master.html" },
    { name: "Fitness Empire", url: "https://ander55555.github.io/games/fitness-empire.html" },
    { name: "Flick Goal", url: "https://ander55555.github.io/games/flick-goal.html" },
    { name: "Flip Master", url: "https://ander55555.github.io/games/flip-master.html" },
    { name: "Giant Wanted", url: "https://ander55555.github.io/games/giant-wanted.html" },
    { name: "Gun Clone", url: "https://ander55555.github.io/games/gun-clone.html" },
    { name: "Gun Runner", url: "https://ander55555.github.io/games/gun-runner.html" },
    { name: "Kaji Run", url: "https://ander55555.github.io/games/kaji-run.html" },
    { name: "Make a SuperBoat", url: "https://ander55555.github.io/games/make-a-superboat.html" },
    { name: "Makeover Run", url: "https://ander55555.github.io/games/makeover-run.html" },
    { name: "Mega Car Jumps", url: "https://ander55555.github.io/games/mega-car-jumps.html" },
    { name: "Money Rush", url: "https://ander55555.github.io/games/money-rush.html" },
    { name: "Monster Box 3D", url: "https://ander55555.github.io/games/monster-box-3d.html" },
    { name: "Office Fight", url: "https://ander55555.github.io/games/office-fight.html" },
    { name: "Robot Invasion", url: "https://ander55555.github.io/games/robot-invasion.html" },
    { name: "Seat Jam 3D", url: "https://ander55555.github.io/games/seat-jam-3d.html" },
    { name: "Shooting Master", url: "https://ander55555.github.io/games/shooting-master.html" },
    { name: "Supermarket 3D", url: "https://ander55555.github.io/games/supermarket-3d.html" },
    { name: "Survive to Victory", url: "https://ander55555.github.io/games/survive-to-victory.html" },
    { name: "Telekinesis Attack", url: "https://ander55555.github.io/games/telekinesis-attack.html" },
    { name: "Telekinesis Car", url: "https://ander55555.github.io/games/telekinesis-car.html" },
    { name: "Telekinesis Drive", url: "https://ander55555.github.io/games/telekinesis-drive.html" },
    { name: "Telekinesis", url: "https://ander55555.github.io/games/telekinesis.html" },
    { name: "Tug of War with Cars", url: "https://ander55555.github.io/games/tug-of-war-with-cars.html" },
    { name: "Twerk Race 3D", url: "https://ander55555.github.io/games/twerk-race-3d.html" },
    { name: "Twisted Rope 3D", url: "https://ander55555.github.io/games/twisted-rope-3d.html" },
    { name: "Wall Crawler", url: "https://ander55555.github.io/games/wall-crawler.html" },
    { name: "War Regions", url: "https://ander55555.github.io/games/war-regions.html" },
    { name: "Weapon Craft Run", url: "https://ander55555.github.io/games/weapon-craft-run.html" },
    { name: "Weapon Upgrade Rush", url: "https://ander55555.github.io/games/weapon-upgrade-rush.html" },
    { name: "Weapon Scale", url: "https://ander55555.github.io/games/weapon-scale.html" },
    { name: "Rich Run 3D", url: "https://ander55555.github.io/games/rich-run-3d.html" },
    { name: "High Heels", url: "https://ander55555.github.io/games/high-heels.html" },
    { name: "WebFishing", url: "https://ander55555.github.io/games/webfishing.html" },
    { name: "Andy's Apple Farm", url: "https://ander55555.github.io/games/andy-s-apple-farm.html" },
    { name: "OMORI", url: "https://ander55555.github.io/games/omori.html" },
    { name: "Five Nights at Freddy's 4: Halloween", url: "https://ander55555.github.io/games/five-nights-at-freddy-s-4-halloween.html" },
    { name: "Code Editor", url: "https://ander55555.github.io/games/code-editor.html" },
    { name: "10 Minutes Till Dawn", url: "https://ander55555.github.io/games/10-minutes-till-dawn.html" },
    { name: "99 Balls", url: "https://ander55555.github.io/games/99-balls.html" },
    { name: "Abandoned", url: "https://ander55555.github.io/games/abandoned.html" },
    { name: "Yume Nikki", url: "https://ander55555.github.io/games/yume-nikki.html" },
    { name: "God's Flesh", url: "https://ander55555.github.io/games/god-s-flesh.html" },
    { name: "A Small World Cup", url: "https://ander55555.github.io/games/a-small-world-cup.html" },
    { name: "Awesome Tanks", url: "https://ander55555.github.io/games/awesome-tanks.html" },
    { name: "Bouncemasters", url: "https://ander55555.github.io/games/bouncemasters.html" },
    { name: "Awesome Tanks 2", url: "https://ander55555.github.io/games/awesome-tanks-2.html" },
    { name: "Bank Robbery 2", url: "https://ander55555.github.io/games/bank-robbery-2.html" },
    { name: "Celeste PICO", url: "https://ander55555.github.io/games/celeste-pico.html" },
    { name: "Kitty Toy", url: "https://ander55555.github.io/games/kitty-toy.html" },
    { name: "Infinimoes", url: "https://ander55555.github.io/games/infinimoes.html" },
    { name: "Adventure Drivers", url: "https://ander55555.github.io/games/adventure-drivers.html" },
    { name: "Ages of Conflict", url: "https://ander55555.github.io/games/ages-of-conflict.html" },
    { name: "Kindergarten", url: "https://ander55555.github.io/games/kindergarten.html" },
    { name: "Kindergarten 2", url: "https://ander55555.github.io/games/kindergarten-2.html" },
    { name: "Nijika's Ahoge", url: "https://ander55555.github.io/games/nijika-s-ahoge.html" },
    { name: "Aquapark.io", url: "https://ander55555.github.io/games/aquapark-io.html" },
    { name: "City Smash", url: "https://ander55555.github.io/games/city-smash.html" },
    { name: "Amanda the Adventurer", url: "https://ander55555.github.io/games/amanda-the-adventurer.html" },
    { name: "Slender: The 8 Pages", url: "https://ander55555.github.io/games/slender-the-8-pages.html" },
    { name: "Station 141", url: "https://ander55555.github.io/games/station-141.html" },
    { name: "Station Saturn", url: "https://ander55555.github.io/games/station-saturn.html" },
    { name: "BLOODMONEY!", url: "https://ander55555.github.io/games/bloodmoney.html" },
    { name: "BERGENTRUCK 201x", url: "https://ander55555.github.io/games/bergentruck-201x.html" },
    { name: "Undertale Yellow", url: "https://ander55555.github.io/games/undertale-yellow.html" },
    { name: "Raft", url: "https://ander55555.github.io/games/raft.html" },
    { name: "The Deadseat", url: "https://ander55555.github.io/games/the-deadseat.html" },
    { name: "The Man In The Window", url: "https://ander55555.github.io/games/the-man-in-the-window.html" },
    { name: "Fears to Fathom: Home Alone", url: "https://ander55555.github.io/games/fears-to-fathom-home-alone.html" },
    { name: "Slither.io", url: "https://ander55555.github.io/games/slither-io.html" },
    { name: "DEAD PLATE", url: "https://ander55555.github.io/games/dead-plate.html" },
    { name: "Lacey's Flash Games", url: "https://ander55555.github.io/games/lacey-s-flash-games.html" },
    { name: "Choppy Orc", url: "https://ander55555.github.io/games/choppy-orc.html" },
    { name: "Cuphead", url: "https://ander55555.github.io/games/cuphead.html" },
    { name: "Baldi's Basics Classic Remastered", url: "https://ander55555.github.io/games/baldi-s-basics-classic-remastered.html" },
    { name: "Baldi's Basics Plus", url: "https://ander55555.github.io/games/baldi-s-basics-plus.html" },
    { name: "Hollow Knight", url: "https://ander55555.github.io/games/hollow-knight.html" },
    { name: "sandstone", url: "https://ander55555.github.io/games/sandstone.html" },
    { name: "Doodle Jump", url: "https://ander55555.github.io/games/doodle-jump.html" },
    { name: "Madness Combat: Project Nexus (classic)", url: "https://ander55555.github.io/games/madness-combat-project-nexus-classic.html" },
    { name: "Bad Time Simulator", url: "https://ander55555.github.io/games/bad-time-simulator.html" },
    { name: "Spacebar Clicker", url: "https://ander55555.github.io/games/spacebar-clicker.html" },
    { name: "Friday Night Funkin': V.S. Whitty", url: "https://ander55555.github.io/games/friday-night-funkin-v-s-whitty.html" },
    { name: "Friday Night Funkin': B-Sides", url: "https://ander55555.github.io/games/friday-night-funkin-b-sides.html" },
    { name: "Friday Night Funkin': Vs. Hex", url: "https://ander55555.github.io/games/friday-night-funkin-vs-hex.html" },
    { name: "Friday Night Funkin': Vs. Hatsune Miku", url: "https://ander55555.github.io/games/friday-night-funkin-vs-hatsune-miku.html" },
    { name: "Friday Night Funkin': Neo", url: "https://ander55555.github.io/games/friday-night-funkin-neo.html" },
    { name: "Steal A Brainrot", url: "https://ander55555.github.io/games/steal-a-brainrot.html" },
    { name: "Friday Night Funkin': Sarvente's Mid-Fight Masses", url: "https://ander55555.github.io/games/friday-night-funkin-sarvente-s-mid-fight-masses.html" },
    { name: "Friday Night Funkin': vs. Tricky", url: "https://ander55555.github.io/games/friday-night-funkin-vs-tricky.html" },
    { name: "Human Expenditure Program", url: "https://ander55555.github.io/games/human-expenditure-program.html" },
    { name: "Friday Night Funkin': Hit Single Real", url: "https://ander55555.github.io/games/friday-night-funkin-hit-single-real.html" },
    { name: "Friday Night Funkin': Creepypasta JP", url: "https://ander55555.github.io/games/friday-night-funkin-creepypasta-jp.html" },
    { name: "Friday Night Funkin': vs. Garcello", url: "https://ander55555.github.io/games/friday-night-funkin-vs-garcello.html" },
    { name: "Friday Night Funkin': Sonic Legacy", url: "https://ander55555.github.io/games/friday-night-funkin-sonic-legacy.html" },
    { name: "Friday Night Funkin': vs. QT", url: "https://ander55555.github.io/games/friday-night-funkin-vs-qt.html" },
    { name: "Friday Night Funkin': Mistful Crimson Morning Reboot", url: "https://ander55555.github.io/games/friday-night-funkin-mistful-crimson-morning-reboot.html" },
    { name: "Friday Night Funkin': Indie Cross", url: "https://ander55555.github.io/games/friday-night-funkin-indie-cross.html" },
    { name: "Rooftop Snipers 2", url: "https://ander55555.github.io/games/rooftop-snipers-2.html" },
    { name: "I woke up next to you again.", url: "https://ander55555.github.io/games/i-woke-up-next-to-you-again.html" },
    { name: "UNDERWHEELS", url: "https://ander55555.github.io/games/underwheels.html" },
    { name: "RigBMX", url: "https://ander55555.github.io/games/rigbmx.html" },
    { name: "RigBMX 2", url: "https://ander55555.github.io/games/rigbmx-2.html" },
    { name: "groon groon, babey!", url: "https://ander55555.github.io/games/groon-groon-babey.html" },
    { name: "Friday Night Funkin': Jeffy's Endless Aethos", url: "https://ander55555.github.io/games/friday-night-funkin-jeffy-s-endless-aethos.html" },
    { name: "Friday Night Funkin': vs. BOPCITY", url: "https://ander55555.github.io/games/friday-night-funkin-vs-bopcity.html" },
    { name: "Friday Night Funkin': 17 Bucks: Floor 1", url: "https://ander55555.github.io/games/friday-night-funkin-17-bucks-floor-1.html" },
    { name: "Friday Night Funkin': FIRE IN THE HOLE: Lobotomy Dash Funkin'", url: "https://ander55555.github.io/games/friday-night-funkin-fire-in-the-hole-lobotomy-dash-funkin.html" },
    { name: "Friday Night Funkin': TWIDDLEFINGER", url: "https://ander55555.github.io/games/friday-night-funkin-twiddlefinger.html" },
    { name: "Kindergarten 3", url: "https://ander55555.github.io/games/kindergarten-3.html" },
    { name: "Stick With It", url: "https://ander55555.github.io/games/stick-with-it.html" },
    { name: "Five Nights at Candy's", url: "https://ander55555.github.io/games/five-nights-at-candy-s.html" },
    { name: "Five Nights at Candy's 2", url: "https://ander55555.github.io/games/five-nights-at-candy-s-2.html" },
    { name: "Pokemon Red", url: "https://ander55555.github.io/games/pokemon-red.html" },
    { name: "Pokemon Emerald", url: "https://ander55555.github.io/games/pokemon-emerald.html" },
    { name: "The Impossible Quiz", url: "https://ander55555.github.io/games/the-impossible-quiz.html" },
    { name: "Super Mario Bros", url: "https://ander55555.github.io/games/super-mario-bros.html" },
    { name: "Friday Night Funkin’ Soft", url: "https://ander55555.github.io/games/friday-night-funkin-soft.html" },
    { name: "Tomodachi Collection", url: "https://ander55555.github.io/games/tomodachi-collection.html" },
    { name: "Doge Miner", url: "https://ander55555.github.io/games/doge-miner.html" },
    { name: "Final Earth 2", url: "https://ander55555.github.io/games/final-earth-2.html" },
    { name: "Swordfight!!", url: "https://ander55555.github.io/games/swordfight.html" },
    { name: "PortaBoy+", url: "https://ander55555.github.io/games/portaboy.html" },
    { name: "PacMan (Horror)", url: "https://ander55555.github.io/games/pacman-horror.html" },
    { name: "Oshi Oshi Punch!", url: "https://ander55555.github.io/games/oshi-oshi-punch.html" },
    { name: "Nubby's Number Factory", url: "https://ander55555.github.io/games/nubby-s-number-factory.html" },
    { name: "Touhou: Luminous Strike", url: "https://ander55555.github.io/games/touhou-luminous-strike.html" },
    { name: "Generic Fighter Maybe", url: "https://ander55555.github.io/games/generic-fighter-maybe.html" },
    { name: "Dan The Man", url: "https://ander55555.github.io/games/dan-the-man.html" },
    { name: "Bust a Loop", url: "https://ander55555.github.io/games/bust-a-loop.html" },
    { name: "Bad Monday Simulator", url: "https://ander55555.github.io/games/bad-monday-simulator.html" },
    { name: "Touhou Mother", url: "https://ander55555.github.io/games/touhou-mother.html" },
    { name: "Parappa The Rapper", url: "https://ander55555.github.io/games/parappa-the-rapper.html" },
    { name: "Friday Night Funkin': Darkness Takeover", url: "https://ander55555.github.io/games/friday-night-funkin-darkness-takeover.html" },
    { name: "SpongeBob SquarePants: Land Ho!", url: "https://ander55555.github.io/games/spongebob-squarepants-land-ho.html" },
    { name: "SpongeBob SquarePants: SpongeBob Run", url: "https://ander55555.github.io/games/spongebob-squarepants-spongebob-run.html" },
    { name: "SpongeBob SquarePants: Squidward's Sizzlin' Scare", url: "https://ander55555.github.io/games/spongebob-squarepants-squidward-s-sizzlin-scare.html" },
    { name: "SpongeBob SquarePants: Sandy's Sponge Stacker", url: "https://ander55555.github.io/games/spongebob-squarepants-sandy-s-sponge-stacker.html" },
    { name: "SpongeBob SquarePants: Tasty Pastry Party", url: "https://ander55555.github.io/games/spongebob-squarepants-tasty-pastry-party.html" },
    { name: "SpongeBob SquarePants: The Kah-Ray-Tay Squid", url: "https://ander55555.github.io/games/spongebob-squarepants-the-kah-ray-tay-squid.html" },
    { name: "SpongeBob SquarePants: WereSquirrel", url: "https://ander55555.github.io/games/spongebob-squarepants-weresquirrel.html" },
    { name: "SpongeBob SquarePants: Krabby Katch", url: "https://ander55555.github.io/games/spongebob-squarepants-krabby-katch.html" },
    { name: "Teen Titans GO!: Jump Jousts", url: "https://ander55555.github.io/games/teen-titans-go-jump-jousts.html" },
    { name: "Teen Titans GO!: Jump Jousts 2", url: "https://ander55555.github.io/games/teen-titans-go-jump-jousts-2.html" },
    { name: "Cat Connection", url: "https://ander55555.github.io/games/cat-connection.html" },
    { name: "Cat Gunner: Super Zombie Shoot", url: "https://ander55555.github.io/games/cat-gunner-super-zombie-shoot.html" },
    { name: "Love Letters", url: "https://ander55555.github.io/games/love-letters.html" },
    { name: "Chiikawa Puzzle", url: "https://ander55555.github.io/games/chiikawa-puzzle.html" },
    { name: "myTeardrop", url: "https://ander55555.github.io/games/myteardrop.html" },
    { name: "Friday Night Funkin': Pibby: Apocalypse", url: "https://ander55555.github.io/games/friday-night-funkin-pibby-apocalypse.html" },
    { name: "Karlson", url: "https://ander55555.github.io/games/karlson.html" },
    { name: "Jelly Drift", url: "https://ander55555.github.io/games/jelly-drift.html" },
    { name: "Plinko", url: "https://ander55555.github.io/games/plinko.html" },
    { name: "Clash Of Vikings", url: "https://ander55555.github.io/games/clash-of-vikings.html" },
    { name: "Recoil", url: "https://ander55555.github.io/games/recoil.html" },
    { name: "Baseball Bros", url: "https://ander55555.github.io/games/baseball-bros.html" },
    { name: "Football Bros", url: "https://ander55555.github.io/games/football-bros.html" },
    { name: "Sonic the Hedgehog 2: Community's Cut", url: "https://ander55555.github.io/games/sonic-the-hedgehog-2-community-s-cut.html" },
    { name: "Sonic the Hedgehog 3: Angel Island Remastered", url: "https://ander55555.github.io/games/sonic-the-hedgehog-3-angel-island-remastered.html" },
    { name: "Hypper Sandbox", url: "https://ander55555.github.io/games/hypper-sandbox.html" },
    { name: "Aviamasters", url: "https://ander55555.github.io/games/aviamasters.html" },
    { name: "Rolling Sky", url: "https://ander55555.github.io/games/rolling-sky.html" },
    { name: "Yandere Simulator", url: "https://ander55555.github.io/games/yandere-simulator.html" },
    { name: "Friday Night Funkin VS. KAPI", url: "https://ander55555.github.io/games/friday-night-funkin-vs-kapi.html" },
    { name: "Friday Night Funkin VS. Sky", url: "https://ander55555.github.io/games/friday-night-funkin-vs-sky.html" },
    { name: "Getting Over It with Bennett Foddy", url: "https://ander55555.github.io/games/getting-over-it-with-bennett-foddy.html" },
    { name: "Friday Night Funkin Vs. Cyber Sensation", url: "https://ander55555.github.io/games/friday-night-funkin-vs-cyber-sensation.html" },
    { name: "Friday Night Funkin vs Shaggy", url: "https://ander55555.github.io/games/friday-night-funkin-vs-shaggy.html" },
    { name: "Deltatraveler", url: "https://ander55555.github.io/games/deltatraveler.html" },
    { name: "BitGun.io", url: "https://ander55555.github.io/games/bitgun-io.html" },
    { name: "Boom Slingers: Reboom", url: "https://ander55555.github.io/games/boom-slingers-reboom.html" },
    { name: "CG FC 25", url: "https://ander55555.github.io/games/cg-fc-25.html" },
    { name: "Count Masters: Stickman Games", url: "https://ander55555.github.io/games/count-masters-stickman-games.html" },
    { name: "Dalgona Candy Honeycomb Cookie", url: "https://ander55555.github.io/games/dalgona-candy-honeycomb-cookie.html" },
    { name: "Highway Racer", url: "https://ander55555.github.io/games/highway-racer.html" },
    { name: "Highway Racer 2 REMASTERED", url: "https://ander55555.github.io/games/highway-racer-2-remastered.html" },
    { name: "Hula Hoop Race", url: "https://ander55555.github.io/games/hula-hoop-race.html" },
    { name: "Jelly Restaurant", url: "https://ander55555.github.io/games/jelly-restaurant.html" },
    { name: "Layers Roll", url: "https://ander55555.github.io/games/layers-roll.html" },
    { name: "Lazy Jumper", url: "https://ander55555.github.io/games/lazy-jumper.html" },
    { name: "Man Runner 2048", url: "https://ander55555.github.io/games/man-runner-2048.html" },
    { name: "Pottery Master", url: "https://ander55555.github.io/games/pottery-master.html" },
    { name: "Shovel 3D", url: "https://ander55555.github.io/games/shovel-3d.html" },
    { name: "Sky Riders", url: "https://ander55555.github.io/games/sky-riders.html" },
    { name: "Steal Brainrot Online", url: "https://ander55555.github.io/games/steal-brainrot-online.html" },
    { name: "Stickman and Guns", url: "https://ander55555.github.io/games/stickman-and-guns.html" },
    { name: "Super Star Car", url: "https://ander55555.github.io/games/super-star-car.html" },
    { name: "Traffic Rider", url: "https://ander55555.github.io/games/traffic-rider.html" },
    { name: "BuildNow.gg", url: "https://ander55555.github.io/games/buildnow-gg.html" },
    { name: "Friday Night Funkin': Mario's Madness", url: "https://ander55555.github.io/games/friday-night-funkin-mario-s-madness.html" },
    { name: "Friday Night Funkin' vs Hypno Lullaby", url: "https://ander55555.github.io/games/friday-night-funkin-vs-hypno-lullaby.html" },
    { name: "Stone Grass Mowing Simulator", url: "https://ander55555.github.io/games/stone-grass-mowing-simulator.html" },
    { name: "Fallout", url: "https://ander55555.github.io/games/fallout.html" },
    { name: "The Oregon Trail", url: "https://ander55555.github.io/games/the-oregon-trail.html" },
    { name: "Newgrounds Rumble", url: "https://ander55555.github.io/games/newgrounds-rumble.html" },
    { name: "Super Mario 64", url: "https://ander55555.github.io/games/super-mario-64.html" },
    { name: "Sonic CD", url: "https://ander55555.github.io/games/sonic-cd.html" },
    { name: "Sonic Mania", url: "https://ander55555.github.io/games/sonic-mania.html" },
    { name: "Slime Rancher", url: "https://ander55555.github.io/games/slime-rancher.html" },
    { name: "Pac Man World", url: "https://ander55555.github.io/games/pac-man-world.html" },
    { name: "Pac Man World 2", url: "https://ander55555.github.io/games/pac-man-world-2.html" },
    { name: "Waterworks!", url: "https://ander55555.github.io/games/waterworks.html" },
    { name: "Shapez.io", url: "https://ander55555.github.io/games/shapez-io.html" },
    { name: "[!] COMMENTS", url: "https://ander55555.github.io/games/comments.html" },
    { name: "Plants vs. Zombies 2 Gardenless", url: "https://ander55555.github.io/games/plants-vs-zombies-2-gardenless.html" },
    { name: "Sonic.EXE", url: "https://ander55555.github.io/games/sonic-exe.html" },
    { name: "Metal Gear Solid", url: "https://ander55555.github.io/games/metal-gear-solid.html" },
    { name: "FNF Vs. Hypno's Lullaby v2", url: "https://ander55555.github.io/games/fnf-vs-hypno-s-lullaby-v2.html" },
    { name: "FNF Vs. Sonic.EXE 3.0/4.0", url: "https://ander55555.github.io/games/fnf-vs-sonic-exe-3-0-4-0.html" },
    { name: "Doom 2", url: "https://ander55555.github.io/games/doom-2.html" },
    { name: "Growden.io", url: "https://ander55555.github.io/games/growden-io.html" },
    { name: "Minesweeper Plus", url: "https://ander55555.github.io/games/minesweeper-plus.html" },
    { name: "Schoolboy Runaway", url: "https://ander55555.github.io/games/schoolboy-runaway.html" },
    { name: "Sonic.EXE (ORIGINAL)", url: "https://ander55555.github.io/games/sonic-exe-original.html" },
    { name: "Tattletail", url: "https://ander55555.github.io/games/tattletail.html" },
    { name: "Friday Night Funkin VS Impostor v4", url: "https://ander55555.github.io/games/friday-night-funkin-vs-impostor-v4.html" },
    { name: "Friday Night Funkin vs Sunday Remastered HD", url: "https://ander55555.github.io/games/friday-night-funkin-vs-sunday-remastered-hd.html" },
    { name: "Friday Night Funkin vs Carol V2", url: "https://ander55555.github.io/games/friday-night-funkin-vs-carol-v2.html" },
    { name: "The Legend of Zelda Ocarina of Time", url: "https://ander55555.github.io/games/the-legend-of-zelda-ocarina-of-time.html" },
    { name: "The Legend of Zelda Majora's Mask", url: "https://ander55555.github.io/games/the-legend-of-zelda-majora-s-mask.html" },
    { name: "Friday Night Funkin' Drop and Roll, but Playable", url: "https://ander55555.github.io/games/friday-night-funkin-drop-and-roll-but-playable.html" },
    { name: "Toy Rider", url: "https://ander55555.github.io/games/toy-rider.html" },
    { name: "Friday Night Funkin Vs. Dave and Bambi v3", url: "https://ander55555.github.io/games/friday-night-funkin-vs-dave-and-bambi-v3.html" },
    { name: "Friday Night Funkin’ Wednesday's Infidelity", url: "https://ander55555.github.io/games/friday-night-funkin-wednesday-s-infidelity.html" },
    { name: "Postal", url: "https://ander55555.github.io/games/postal.html" },
    { name: "FNF vs Bob v2.0 (Bob’s Onslaught)", url: "https://ander55555.github.io/games/fnf-vs-bob-v2-0-bob-s-onslaught.html" },
    { name: "Friday Night Funkin': Rev-Mixed", url: "https://ander55555.github.io/games/friday-night-funkin-rev-mixed.html" },
    { name: "Three Goblets", url: "https://ander55555.github.io/games/three-goblets.html" },
    { name: "Friday Night Funkin': Gumballs", url: "https://ander55555.github.io/games/friday-night-funkin-gumballs.html" },
    { name: "Oneshot (LEGACY)", url: "https://ander55555.github.io/games/oneshot-legacy.html" },
    { name: "Celeste", url: "https://ander55555.github.io/games/celeste.html" },
    { name: "Happy Wheels", url: "https://ander55555.github.io/games/happy-wheels.html" },
    { name: "Get Yoked", url: "https://ander55555.github.io/games/get-yoked.html" },
    { name: "Doom 3", url: "https://ander55555.github.io/games/doom-3.html" },
    { name: "Tag", url: "https://ander55555.github.io/games/tag.html" },
    { name: "Pizza Tower: Scoutdigo", url: "https://ander55555.github.io/games/pizza-tower-scoutdigo.html" },
    { name: "Off", url: "https://ander55555.github.io/games/off.html" },
    { name: "Space Funeral", url: "https://ander55555.github.io/games/space-funeral.html" },
    { name: "Endroll", url: "https://ander55555.github.io/games/endroll.html" },
    { name: "Cave Story", url: "https://ander55555.github.io/games/cave-story.html" },
    { name: "Friday Night Funkin': VS. Impostor: Alternated", url: "https://ander55555.github.io/games/friday-night-funkin-vs-impostor-alternated.html" },
    { name: "Friday Night Funkin': Chaos Nightmare - Sonic Vs. Fleetway", url: "https://ander55555.github.io/games/friday-night-funkin-chaos-nightmare-sonic-vs-fleetway.html" },
    { name: "Spelunky Classic HD", url: "https://ander55555.github.io/games/spelunky-classic-hd.html" },
    { name: "Friday Night Funkin' D-Sides", url: "https://ander55555.github.io/games/friday-night-funkin-d-sides.html" },
    { name: "BFDIA 5b", url: "https://ander55555.github.io/games/bfdia-5b.html" },
    { name: "BFDIA 5b: 5*30", url: "https://ander55555.github.io/games/bfdia-5b-5-30.html" },
    { name: "Friday Night Funkin' VS Impostor B-Sides", url: "https://ander55555.github.io/games/friday-night-funkin-vs-impostor-b-sides.html" },
    { name: "Mutilate a Doll 2", url: "https://ander55555.github.io/games/mutilate-a-doll-2.html" },
    { name: "Godzilla Daikaiju Battle Royale", url: "https://ander55555.github.io/games/godzilla-daikaiju-battle-royale.html" },
    { name: "Friday Night Funkin' Sunday Night Suicide: Rookies Edition", url: "https://ander55555.github.io/games/friday-night-funkin-sunday-night-suicide-rookies-edition.html" },
    { name: "Rio Rex", url: "https://ander55555.github.io/games/rio-rex.html" },
    { name: "Friday Night Funkin vs Nonsense", url: "https://ander55555.github.io/games/friday-night-funkin-vs-nonsense.html" },
    { name: "Arthur's Nightmare", url: "https://ander55555.github.io/games/arthur-s-nightmare.html" },
    { name: "Buster Jam", url: "https://ander55555.github.io/games/buster-jam.html" },
    { name: "Super Smash Flash", url: "https://ander55555.github.io/games/super-smash-flash.html" },
    { name: "Mindwave", url: "https://ander55555.github.io/games/mindwave.html" },
    { name: "Look Outside", url: "https://ander55555.github.io/games/look-outside.html" },
    { name: "Milk Inside a Bag of Milk Inside a Bag of Milk", url: "https://ander55555.github.io/games/milk-inside-a-bag-of-milk-inside-a-bag-of-milk.html" },
    { name: "Milk Outside A Bag Of Milk Outside A Bag Of Milk", url: "https://ander55555.github.io/games/milk-outside-a-bag-of-milk-outside-a-bag-of-milk.html" },
    { name: "1 Date Danger", url: "https://ander55555.github.io/games/1-date-danger.html" },
    { name: "Final Fantasy VII", url: "https://ander55555.github.io/games/final-fantasy-vii.html" },
    { name: "Goblin Goopmaxxing", url: "https://ander55555.github.io/games/goblin-goopmaxxing.html" },
    { name: "Rogue Sergeant The Final Operation", url: "https://ander55555.github.io/games/rogue-sergeant-the-final-operation.html" },
    { name: "Friday Night Funkin vs Undertale", url: "https://ander55555.github.io/games/friday-night-funkin-vs-undertale.html" },
    { name: "Midnight Shift", url: "https://ander55555.github.io/games/midnight-shift.html" },
    { name: "Orange Roulette", url: "https://ander55555.github.io/games/orange-roulette.html" },
    { name: "Please Dont Touch Anything", url: "https://ander55555.github.io/games/please-dont-touch-anything.html" },
    { name: "Royal Towers: Medieval TD", url: "https://ander55555.github.io/games/royal-towers-medieval-td.html" },
    { name: "Going Balls", url: "https://ander55555.github.io/games/going-balls.html" },
    { name: "3D Bolt Master", url: "https://ander55555.github.io/games/3d-bolt-master.html" },
    { name: "Tall.io", url: "https://ander55555.github.io/games/tall-io.html" },
    { name: "Match Triple 3D", url: "https://ander55555.github.io/games/match-triple-3d.html" },
    { name: "Stick War: Legacy", url: "https://ander55555.github.io/games/stick-war-legacy.html" },
    { name: "In Stars and Time", url: "https://ander55555.github.io/games/in-stars-and-time.html" },
    { name: "Gorilla Tag", url: "https://ander55555.github.io/games/gorilla-tag.html" },
    { name: "Drive", url: "https://slowroads.io" },
    { name: "Minecraft", url: "https://eaglercraft.ir/play/1.12.2" },
    { name: "FNAF", url: "https://fnaf.gg" },
    { name: "Math", url: "https://gauthmath.com" },
    { name: "Dead Shot", url: "https://deadshot.io" },
    { name: "Ships3D", url: "https://yp3d.com/ships3d" },
    { name: "Escape Road", url: "https://escaperoad.io/escape-road" },
    { name: "RetroBowl", url: "https://retrobowl.gg" },
    { name: "DuckMath", url: "https://duckmath.org" },
    { name: "Yohoho", url: "https://yohoho.io" },
    { name: "Cod Zombies", url: "https://nzp.gay" },
    { name: "Chill", url: "https://app.chillhop.com" },
    { name: "Pluto TV", url: "https://pluto.tv/" },
    { name: "Drift Hunters", url: "https://drifthunters.com" },
    { name: "Townscaper", url: "https://oskarstalberg.com/Townscaper/" },
    { name: "Drivemad", url: "https://drivemad.com" },
    { name: "Smash Karts", url: "https://smashkarts.io" },
    { name: "Cookie Clicker", url: "https://cookieclicker.org" },
    { name: "MaddoxCloud", url: "https://maddoxcloud.com" }
    ];

    function getFavicon(url) {
        const host = new URL(url).hostname;
        return `https://www.google.com/s2/favicons?sz=128&domain=${host}`;
    }

    function trackPlay(gameName) {
        let stats = JSON.parse(localStorage.getItem('gameStats') || '{}');
        stats[gameName] = (stats[gameName] || 0) + 1;
        localStorage.setItem('gameStats', JSON.stringify(stats));
    }

    function getPinnedGames() {
        let stats = JSON.parse(localStorage.getItem('gameStats') || '{}');
        return Object.entries(stats)
            .sort((a, b) => b[1] - a[1])
            .slice(0, 3)
            .filter(item => item[1] > 0)
            .map(item => games.find(g => g.name === item[0]))
            .filter(g => g !== undefined);
    }

function createCard(game) {
        const card = document.createElement('article');
        card.className = 'game';

        // LOGIC: Use the custom icon if it exists, otherwise use the favicon
        const iconSrc = game.icon ? game.icon : getFavicon(game.url);

        card.innerHTML = `
            <div class="thumb">
                <img src="${iconSrc}" alt="" onerror="this.src='${getFavicon(game.url)}'">
            </div>
            <div>
                <div class="title">${game.name}</div>
                <div class="meta">${new URL(game.url).hostname.replace('www.', '')}</div>
            </div>
        `;
        card.onclick = () => {
            trackPlay(game.name);
            launchGame(game.url);
        };
        return card;
    }

    function renderLibrary(term = "") {
        const container = document.getElementById('home');
        const pinnedContainer = document.getElementById('pinned-home');
        const pinnedWrapper = document.getElementById('pinned-section');
        
        container.innerHTML = "";
        pinnedContainer.innerHTML = "";

        // Handle Pinned Games (only show if not searching)
        if (term === "") {
            const pinned = getPinnedGames();
            if (pinned.length > 0) {
                pinnedWrapper.style.display = "block";
                pinned.forEach(game => pinnedContainer.appendChild(createCard(game)));
            } else {
                pinnedWrapper.style.display = "none";
            }
        } else {
            pinnedWrapper.style.display = "none";
        }

        // Handle All Games
        const filtered = games.filter(g => g.name.toLowerCase().includes(term.toLowerCase()));
        filtered.forEach(game => container.appendChild(createCard(game)));
    }

    function playRandom() {
        const randomGame = games[Math.floor(Math.random() * games.length)];
        launchGame(randomGame.url);
    }

    document.getElementById('search-input').addEventListener('input', (e) => renderLibrary(e.target.value));

    function launchGame(url) {
        document.body.classList.add('fullscreen');
        const view = document.createElement('div');
        view.className = 'fullscreen-container';
        view.id = 'game-overlay';
        view.innerHTML = `
            <div class="game-controls">
                <button class="glass-btn" onclick="closeGame()">←</button>
                <button class="glass-btn" onclick="toggleFull()">⛶</button>
            </div>
            <iframe id="game-iframe" src="${url}" allowfullscreen sandbox="allow-scripts allow-same-origin allow-pointer-lock allow-forms allow-popups"></iframe>
        `;
        document.body.appendChild(view);
    }

    function toggleFull() {
        const iframe = document.getElementById('game-iframe');
        if (iframe.requestFullscreen) iframe.requestFullscreen();
        else if (iframe.webkitRequestFullscreen) iframe.webkitRequestFullscreen();
    }

    function closeGame() {
        const overlay = document.getElementById('game-overlay');
        if(overlay) overlay.remove();
        document.body.classList.remove('fullscreen');
        renderLibrary(); // Re-render to update pins
    }

    window.addEventListener('keydown', (e) => {
        if (e.key === 'Escape') closeGame();
    });

    document.addEventListener('DOMContentLoaded', () => renderLibrary());
